/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aeontanvir;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author aeon
 */
public class LoginFrame extends javax.swing.JFrame {
    int loginTry = 1;
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();

        //setLocation
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        panForBg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLogPassword = new javax.swing.JPasswordField();
        txtLogUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblBg = new javax.swing.JLabel();
        btnsignup = new javax.swing.JButton();

        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        setTitle("登陆");
        setName("loginFrame"); // NOI18N
        setResizable(false);

        panForBg.setLayout(null);
        //用户名Label定义
        jLabel2.setFont(new java.awt.Font("黑体", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("用    户");
        panForBg.add(jLabel2);
        jLabel2.setBounds(60, 140, 80, 17);
        //密码label定义
        jLabel3.setFont(new java.awt.Font("黑体", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("密    码");
        panForBg.add(jLabel3);
        jLabel3.setBounds(60, 190, 80, 17);
        //密码输入框定义
        txtLogPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panForBg.add(txtLogPassword);
        txtLogPassword.setBounds(170, 180, 240, 30);
        //用户名输入框定义
        txtLogUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panForBg.add(txtLogUsername);
        txtLogUsername.setBounds(170, 130, 240, 30);
        //大标题定义
        jLabel1.setFont(new java.awt.Font("黑体", Font.BOLD, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("多功能记账本");
        panForBg.add(jLabel1);
        jLabel1.setBounds(210, 70, 150, 30);
        //登陆按钮定义
        btnLogin.setFont(new java.awt.Font("黑体", 1, 15)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("登 陆");
        panForBg.add(btnLogin);
        btnLogin.setBounds(320, 230, 90, 40);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        //注册按钮定义
        btnsignup.setFont(new java.awt.Font("黑体", 1, 15)); // NOI18N
        btnsignup.setForeground(new java.awt.Color(0, 0, 0));
        btnsignup.setText("注 册");
        panForBg.add(btnsignup);
        btnsignup.setBounds(100, 230, 90, 40);
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        //大标题Icon定义
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aeontanvir/img/logkey.png"))); // NOI18N
        panForBg.add(jLabel4);
        jLabel4.setBounds(160, 60, 50, 50);

        //作者信息定义
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("2019SCNU");
        panForBg.add(jLabel5);
        jLabel5.setBounds(280, 290, 200, 20);

        //登陆界面Icon定义
        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aeontanvir/img/login.jpg"))); // NOI18N
        panForBg.add(lblBg);
        lblBg.setBounds(0, 0, 490, 330);
        //定义Layout形式
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        //水平lLayout
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panForBg, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );
        //垂直Layout
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panForBg, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
    }

    private void clean_all(){
        Connection conn = null;
        PreparedStatement pstm = null;
        ResultSet rs = null;
        try{
            String status = "在线";
            conn = DatabaseConnection.getConnection();
            String sql = "Update user set status = '"
                    +"' where status = '"
                    + status
                    +"'";
            System.out.println(sql);
            pstm = conn.prepareStatement(sql);
            pstm.executeUpdate();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void setuser(String name){
        Connection conn = null;
        PreparedStatement pstm = null;
        ResultSet rs = null;
        try{
            String status = "在线";
            conn = DatabaseConnection.getConnection();
            String sql = "Update user set status = '"
                    + status
                    +"' where username = '"
                    + name
                    +"'";
            System.out.println(sql);
            pstm = conn.prepareStatement(sql);
            pstm.executeUpdate();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
        //登陆界面的判断
        //若无输入用户名或者密码则提示
        if ("".equals(txtLogUsername.getText())) {
            JOptionPane.showMessageDialog(rootPane, "请输入用户名！！！");
            txtLogUsername.requestFocus();
        } else if ("".equals(txtLogPassword.getText())) {
            JOptionPane.showMessageDialog(rootPane, "请输入密码！！！");
            txtLogPassword.requestFocus();
        } else {
            Connection conn = null;
            PreparedStatement pstm = null;
            ResultSet rs = null;
            try {
                conn = DatabaseConnection.getConnection();
                String sql = "SELECT * FROM user WHERE username = ? and password = ?";
                pstm = conn.prepareStatement(sql);
                pstm.setString(1, txtLogUsername.getText());
                pstm.setString(2, txtLogPassword.getText());
                rs = pstm.executeQuery();
                if (rs.next()) {
                    ErrorHelper.login("登陆主界面—— " + "用户名 "+txtLogUsername.getText());
                    String username = txtLogUsername.getText();
                    try {
                        clean_all();
                        setuser(username);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    txtLogUsername.setText("");
                    txtLogPassword.setText("");
                    //进入主界面
                    MainFrame mainFrame = new MainFrame();
                    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                    mainFrame.setLocation(dim.width / 2 - mainFrame.getSize().width / 2, dim.height / 2 - mainFrame.getSize().height / 2);
                    mainFrame.setVisible(true);
                } else {
                    //错误输入账号密码登陆6次则退出系统
                    loginTry = loginTry + 1;
                    if(loginTry == 6){
                        ErrorHelper.loginError("输入错误次数已达六次，系统退出 - "+"错误的账号与密码： " + txtLogUsername.getText() + "|" + txtLogPassword.getText());
                        System.exit(1);
                    }
                    JOptionPane.showMessageDialog(rootPane, "账号密码错误，请重新输入！！");
                    ErrorHelper.loginError("错误的账号与密码： " + txtLogUsername.getText() + "|" + txtLogPassword.getText());
                    txtLogPassword.setText("");
                    txtLogPassword.requestFocus();
                }

            } catch (Exception e) {
                try {
                    ErrorHelper.exceptionError("LoginFrame btnLoginActionPerformed Error \t" + e);
                } catch (Exception ex) {
                    System.err.println("123654753");
                }
                System.err.println("LoginFrame btnLoginActionPerformed Error \t" + e);
            }finally{
                try {
                    conn.close();
                    pstm.close();
                    rs.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }
    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {
        //登陆界面的判断
        //若无输入用户名或者密码则提示
        SignupFrame signupFrame = new SignupFrame();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        signupFrame.setLocation(dim.width / 2 - signupFrame.getSize().width / 2, dim.height / 2 - signupFrame.getSize().height / 2);
        signupFrame.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    //变量定义
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBg;
    private javax.swing.JPanel panForBg;
    private javax.swing.JPasswordField txtLogPassword;
    private javax.swing.JTextField txtLogUsername;
    // End of variables declaration//GEN-END:variables
}
